name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Check terraform script
      - name: Validate terraform scripts
        run: |
          cd ${{ github.workspace }}/terraform/Provision-VNet-Infrastructure
          terraform init
          terraform validate

      - name: Install terraform compliance
        run: |
          pip install terraform-compliance

      - name: Run terraform compliance tests
        uses: azure/CLI@v1
        with:
          azcliversion: 2.26.1
          inlineScript: |
            az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} \
                    --tenant ${{ secrets.TENANT_ID }}
            cd ${{ github.workspace }}/terraform/Provision-VNet-Infrastructure
            terraform plan -out=plan.tfplan -var='enable_vnet=true'
            terraform show --json plan.tfplan > plan.tfplan.json
            terraform-compliance -p plan.tfplan.json -f ${{ github.workspace }}/terraform/features/

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.26.1
          inlineScript: |
            az logout
            az cache purge
            az account clear